### ISSUE TITLE
Images for testing CustomEntityLookup skill show incorrect information

### ISSUE THREAD

**Issue by storey247** [Azure-Samples/azure-search-knowledge-mining#60]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

- The images on Workshop 3 under the heading "Testing the Azure Function" seem to make reference to a "custom-search" skill and are confusing

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi Dave - thanks for pointing that out. It looks like the screenshot should say `custom-entity-lookup` rather than `custom-search` because `custom-entity-lookup` is the name given to the Azure Function in this [file](https://github.com/Azure-Samples/azure-search-power-skills/blob/master/Text/CustomEntitySearch/CustomEntityLookup.cs).

Does that sound right to you?

**Comment by storey247** [comment]
Hi @dereklegenzoff yes that sounds right to me. The text all seems correct but the example screenshots need updating to remove `custom-search` references 👍
